### ISSUE TITLE
Supersonic shear imaging

### ISSUE THREAD

**Issue by RemiDelaunay** [mlp6/fem#100]
Hi,

I found this repository by reading your paper : "Guidelines for Finite-Element Modeling of Acoustic Radiation Force-Induced Shear Wave Propagation in Tissue-Mimicking Media". Thanks a lot for open-sourcing your work. I am interested in creating a supersonic shear imaging (SSI) simulation dataset. I could only find examples for single-push elastography. Would it be possible to use your package to generate SSI data ?

Best,

Remi Delaunay

**Comment by mlp6** [comment]
@RemiDelaunay we have used these tools for that purpose before (example: https://doi.org/10.1109/TUFFC.2014.006594); but the excitation has to be manually created using one of two approaches:

1. You can do multiple Field II simulations, one for each focal depth, and superpose those intensity fields to create a single intensity field to create the point loads.  This approach neglects the timing offset between the start/finish of each sequential excitation at discrete focal depths.
2. You can run multiple FEM simulations for each single-focus excitation, which can take into account the different start/end times of the impulsive excitation, and then superpose the FEM outputs.  We've used this approach in the past to evaluate the effects of the timing of the excitations (shallow -> deep foci, vs. deep -> shallow foci).

Since we decouple the acoustic simulation from the resultant tissue dynamics, you can choose what assumptions are best for your problem.

I hope this helps!

**Comment by RemiDelaunay** [comment]
@mlp6 Thank you for your detailed answer. It does help a lot !

I suppose the second solution is preferable to account for the time offset for each push. When you say 'superpose the FEM outputs', do you mean I would just need to sum the resulting displacement data for each single-focus excitation by considering the time difference between each push (in order to obtain the 'cone' shape) ? Would it requires any normalisation/pre-processing step prior the sum operation in that case ?

Remi

**Comment by mlp6** [comment]
@RemiDelaunay yep - just doing a temporally-aligned summation should work since this is all simulated as a linear system.  W/r to normalization, you can take that into account w/ how you scale the Isppa for each excitation if you have experimental data to set this magnitude, or let Field II take into account the attenuation effects for each case.

**Comment by RemiDelaunay** [comment]
Great I will try that then. Thank you !
