### ISSUE TITLE
Questions for ARF simulation with Field-II

### ISSUE THREAD

**Issue by RemiDelaunay** [mlp6/fem#101]
Hi,

I have been using your package to simulate shear wave propagation to work on ultrasound tracking algorithm. I have run several half-symmetry simulations in an elastic digital phantom (30 cm x 30 cm x 10 cm), varying the mesh node spacing (from 0.16 to 0.5 mm). I used FEM parameters similar to "Guidelines for Finite-Element Modeling of Acoustic Radiation Force-Induced Shear Wave Propagation in Tissue-Mimicking Media", i.e., F/N=2, push duration of  70μs simulated with field-II using probe parameters from "linear.m".  However, the resulting displacement data seems quite "noisy" compared to the results showed in the paper mentioned above (see figure below with a node spacing of 0.16mm). Therefore, I am wondering whether I am missing a post-processing step ( normalizing displacements ?) or if there is something wrong with my simulation.

![sw_propagation](https://user-images.githubusercontent.com/43678034/120690243-dd334880-c49c-11eb-92ca-83eb04e1fabf.png)

I was also wondering about the influence of the mesh node spacing on displacements measured with ultrasound tracking methods because as you are well aware the node spacing has a high impact on the computation time. Does a node spacing of 0.35 mm for example would be enough to properly model the displacement induced by the ARF, when tracking displacement from ultrasound simulations ?

Thank you

**Comment by mlp6** [comment]
@RemiDelaunay the sim looks correct, but it might be influenced by a few factors related to the extent of your excitation relative to the mesh size.  

Do you have PMLs on the non-symmetry faces?  By 13.9 ms, your shear waves have definitely interacted with those edges, and I don't see strong reflections back into the model, so I'm guessing yes... but sometimes those PMLs can cause some distortions at the boundary that affect the adjacent non-PML elements.  You could either increase the number of PML elements (maybe up to 10?), or push those boundaries out some so that you have more time to avoid that interaction.  The elevation depth of your excitation might also be interacting with the back plane that you cannot see, which can cause similar distortions to creep in.

More importantly, I think you might have some "jiggling" of the mesh.  Your excitation approaches relatively close to the bottom, and I'm guessing you have some finite speed compressional waves that are resonating between the top and bottom boundaries, which is causing some of the "ringing" you see, which gets worse later in time.  One way to deal with that would be to make the mesh deeper to push those boundaries farther apart... or you could introduce a bit of additional numerical damping to help suppress those compressional waves.

**Comment by RemiDelaunay** [comment]
@mlp6 Thank you for your guidance. I don't have a lot of experience in FEM simulation so it's good to know what I am getting make sense. I did add some PML but not up to 10 elements. 

I am trying to limit the mesh dimension to reduce the number of nodes per mesh. I am using LSDYNA student (limited to 128k nodes...). Do you think it would be better to have a larger node spacing to increase the phantom dimension ? It's hard to determine the right trade-off between node spacing/mesh size.

**Comment by mlp6** [comment]
@RemiDelaunay if you are willing to run several iteration of the model, you can look at how mesh refinement affects the captured excitation and resultant shear wave morphology, and choose the crudest node spacing that you can get away with.  You can do the same with your overall mesh dimensions, and evaluate if you are seeing an effect of the finite mesh size (at least in the region where you need for your data to be the most reliable).

Additionally, if you choose a shallower excitation, you don't have to simulate something as deep, and you can reduce the overall mesh size that way.

**Comment by RemiDelaunay** [comment]
Thank you  @mlp6 this is really helpful. I will start with that 👍 :)
